//
//  Data.swift
//  SearchBar
//
//  Created by Thibault GODEFROY on 06/06/2023.
//

import Foundation

// MARK: - CountryRepository
struct CountryRepository {
    let countries: [Country] = [
        Country(name: "Afghanistan"),
        Country(name: "Albania"),
        Country(name: "Algeria"),
        Country(name: "American Samoa"),
        Country(name: "Andorra"),
        Country(name: "Angola"),
        Country(name: "Anguilla"),
        Country(name: "Antarctica"),
        Country(name: "Antigua and Barbuda"),
        Country(name: "Argentina"),
        Country(name: "Armenia"),
        Country(name: "Aruba"),
        Country(name: "Australia"),
        Country(name: "Austria"),
        Country(name: "Azerbaijan"),
        Country(name: "Bahamas (the)"),
        Country(name: "Bahrain"),
        Country(name: "Bangladesh"),
        Country(name: "Barbados"),
        Country(name: "Belarus"),
        Country(name: "Belgium"),
        Country(name: "Belize"),
        Country(name: "Benin"),
        Country(name: "Bermuda"),
        Country(name: "Bhutan"),
        Country(name: "Bolivia (Plurinational State of)"),
        Country(name: "Bonaire, Sint Eustatius and Saba"),
        Country(name: "Bosnia and Herzegovina"),
        Country(name: "Botswana"),
        Country(name: "Bouvet Island"),
        Country(name: "Brazil"),
        Country(name: "British Indian Ocean Territory (the)"),
        Country(name: "Brunei Darussalam"),
        Country(name: "Bulgaria"),
        Country(name: "Burkina Faso"),
        Country(name: "Burundi"),
        Country(name: "Cabo Verde"),
        Country(name: "Cambodia"),
        Country(name: "Cameroon"),
        Country(name: "Canada"),
        Country(name: "Cayman Islands (the)"),
        Country(name: "Central African Republic (the)"),
        Country(name: "Chad"),
        Country(name: "Chile"),
        Country(name: "China"),
        Country(name: "Christmas Island"),
        Country(name: "Cocos (Keeling) Islands (the)"),
        Country(name: "Colombia"),
        Country(name: "Comoros (the)"),
        Country(name: "Congo (the Democratic Republic of the)"),
        Country(name: "Congo (the)"),
        Country(name: "Cook Islands (the)"),
        Country(name: "Costa Rica"),
        Country(name: "Croatia"),
        Country(name: "Cuba"),
        Country(name: "Curaçao"),
        Country(name: "Cyprus"),
        Country(name: "Czechia"),
        Country(name: "Côte d'Ivoire"),
        Country(name: "Denmark"),
        Country(name: "Djibouti"),
        Country(name: "Dominica"),
        Country(name: "Dominican Republic (the)"),
        Country(name: "Ecuador"),
        Country(name: "Egypt"),
        Country(name: "El Salvador"),
        Country(name: "Equatorial Guinea"),
        Country(name: "Eritrea"),
        Country(name: "Estonia"),
        Country(name: "Eswatini"),
        Country(name: "Ethiopia"),
        Country(name: "Falkland Islands (the) [Malvinas]"),
        Country(name: "Faroe Islands (the)"),
        Country(name: "Fiji"),
        Country(name: "Finland"),
        Country(name: "France"),
        Country(name: "French Guiana"),
        Country(name: "French Polynesia"),
        Country(name: "French Southern Territories (the)"),
        Country(name: "Gabon"),
        Country(name: "Gambia (the)"),
        Country(name: "Georgia"),
        Country(name: "Germany"),
        Country(name: "Ghana"),
        Country(name: "Gibraltar"),
        Country(name: "Greece"),
        Country(name: "Greenland"),
        Country(name: "Grenada"),
        Country(name: "Guadeloupe"),
        Country(name: "Guam"),
        Country(name: "Guatemala"),
        Country(name: "Guernsey"),
        Country(name: "Guinea"),
        Country(name: "Guinea-Bissau"),
        Country(name: "Guyana"),
        Country(name: "Haiti"),
        Country(name: "Heard Island and McDonald Islands"),
        Country(name: "Holy See (the)"),
        Country(name: "Honduras"),
        Country(name: "Hong Kong"),
        Country(name: "Hungary"),
        Country(name: "Iceland"),
        Country(name: "India"),
        Country(name: "Indonesia"),
        Country(name: "Iran (Islamic Republic of)"),
        Country(name: "Iraq"),
        Country(name: "Ireland"),
        Country(name: "Isle of Man"),
        Country(name: "Israel"),
        Country(name: "Italy"),
        Country(name: "Jamaica"),
        Country(name: "Japan"),
        Country(name: "Jersey"),
        Country(name: "Jordan"),
        Country(name: "Kazakhstan"),
        Country(name: "Kenya"),
        Country(name: "Kiribati"),
        Country(name: "Korea (the Democratic People's Republic of)"),
        Country(name: "Korea (the Republic of)"),
        Country(name: "Kuwait"),
        Country(name: "Kyrgyzstan"),
        Country(name: "Lao People's Democratic Republic (the)"),
        Country(name: "Latvia"),
        Country(name: "Lebanon"),
        Country(name: "Lesotho"),
        Country(name: "Liberia"),
        Country(name: "Libya"),
        Country(name: "Liechtenstein"),
        Country(name: "Lithuania"),
        Country(name: "Luxembourg"),
        Country(name: "Macao"),
        Country(name: "Madagascar"),
        Country(name: "Malawi"),
        Country(name: "Malaysia"),
        Country(name: "Maldives"),
        Country(name: "Mali"),
        Country(name: "Malta"),
        Country(name: "Marshall Islands (the)"),
        Country(name: "Martinique"),
        Country(name: "Mauritania"),
        Country(name: "Mauritius"),
        Country(name: "Mayotte"),
        Country(name: "Mexico"),
        Country(name: "Micronesia (Federated States of)"),
        Country(name: "Moldova (the Republic of)"),
        Country(name: "Monaco"),
        Country(name: "Mongolia"),
        Country(name: "Montenegro"),
        Country(name: "Montserrat"),
        Country(name: "Morocco"),
        Country(name: "Mozambique"),
        Country(name: "Myanmar"),
        Country(name: "Namibia"),
        Country(name: "Nauru"),
        Country(name: "Nepal"),
        Country(name: "Netherlands (the)"),
        Country(name: "New Caledonia"),
        Country(name: "New Zealand"),
        Country(name: "Nicaragua"),
        Country(name: "Niger (the)"),
        Country(name: "Nigeria"),
        Country(name: "Niue"),
        Country(name: "Norfolk Island"),
        Country(name: "Northern Mariana Islands (the)"),
        Country(name: "Norway"),
        Country(name: "Oman"),
        Country(name: "Pakistan"),
        Country(name: "Palau"),
        Country(name: "Palestine, State of"),
        Country(name: "Panama"),
        Country(name: "Papua New Guinea"),
        Country(name: "Paraguay"),
        Country(name: "Peru"),
        Country(name: "Philippines (the)"),
        Country(name: "Pitcairn"),
        Country(name: "Poland"),
        Country(name: "Portugal"),
        Country(name: "Puerto Rico"),
        Country(name: "Qatar"),
        Country(name: "Republic of North Macedonia"),
        Country(name: "Romania"),
        Country(name: "Russian Federation (the)"),
        Country(name: "Rwanda"),
        Country(name: "Réunion"),
        Country(name: "Saint Barthélemy"),
        Country(name: "Saint Helena, Ascension and Tristan da Cunha"),
        Country(name: "Saint Kitts and Nevis"),
        Country(name: "Saint Lucia"),
        Country(name: "Saint Martin (French part)"),
        Country(name: "Saint Pierre and Miquelon"),
        Country(name: "Saint Vincent and the Grenadines"),
        Country(name: "Samoa"),
        Country(name: "San Marino"),
        Country(name: "Sao Tome and Principe"),
        Country(name: "Saudi Arabia"),
        Country(name: "Senegal"),
        Country(name: "Serbia"),
        Country(name: "Seychelles"),
        Country(name: "Sierra Leone"),
        Country(name: "Singapore"),
        Country(name: "Sint Maarten (Dutch part)"),
        Country(name: "Slovakia"),
        Country(name: "Slovenia"),
        Country(name: "Solomon Islands"),
        Country(name: "Somalia"),
        Country(name: "South Africa"),
        Country(name: "South Georgia and the South Sandwich Islands"),
        Country(name: "South Sudan"),
        Country(name: "Spain"),
        Country(name: "Sri Lanka"),
        Country(name: "Sudan (the)"),
        Country(name: "Suriname"),
        Country(name: "Svalbard and Jan Mayen"),
        Country(name: "Sweden"),
        Country(name: "Switzerland"),
        Country(name: "Syrian Arab Republic"),
        Country(name: "Taiwan"),
        Country(name: "Tajikistan"),
        Country(name: "Tanzania, United Republic of"),
        Country(name: "Thailand"),
        Country(name: "Timor-Leste"),
        Country(name: "Togo"),
        Country(name: "Tokelau"),
        Country(name: "Tonga"),
        Country(name: "Trinidad and Tobago"),
        Country(name: "Tunisia"),
        Country(name: "Turkey"),
        Country(name: "Turkmenistan"),
        Country(name: "Turks and Caicos Islands (the)"),
        Country(name: "Tuvalu"),
        Country(name: "Uganda"),
        Country(name: "Ukraine"),
        Country(name: "United Arab Emirates (the)"),
        Country(name: "United Kingdom of Great Britain and Northern Ireland (the)"),
        Country(name: "United States Minor Outlying Islands (the)"),
        Country(name: "United States of America (the)"),
        Country(name: "Uruguay"),
        Country(name: "Uzbekistan"),
        Country(name: "Vanuatu"),
        Country(name: "Venezuela (Bolivarian Republic of)"),
        Country(name: "Viet Nam"),
        Country(name: "Virgin Islands (British)"),
        Country(name: "Virgin Islands (U.S.)"),
        Country(name: "Wallis and Futuna"),
        Country(name: "Western Sahara"),
        Country(name: "Yemen"),
        Country(name: "Zambia"),
        Country(name: "Zimbabwe"),
        Country(name: "Åland Islands")
    ]
}
